### ISSUE TITLE
Checklist for PRs

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1077]
Example:
https://github.com/json-editor/json-editor/pull/882

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning doesn't seem like the PR and issue were properly linked as this wasn't closed by merging the PR

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yeah I think Github only does that when the line is just "Fixes #..." but that's OK, I still think it's useful to have the link easily visible in the table.

**Comment by brockfanning** [comment]
Some feedback on what we have so far:
The checklist is great and very useful. There are only a couple of awkward bits:
1. The changelog item can not actually be "checked" until the PR is created. This is because changelog entries have to include the PR number, which we don't know until we create it. There's no way around this, but it does mean that, to be totally correct, the PR will need to be created with ❌ and then later updated with ✔️ when the changelog has been added.
2. There are times when I need to add a ❌ or a ✔️ but there is not another one on the page. So I need to either know the keyboard shortcut (eg `:x`) or go find another PR to copy/paste.

One possible solution to these is to use checkboxes for the yes/no questions, and then a table for everything else. For example:

Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.3.0-dev
Bugfix, feature or docs? |

* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

This avoids the need to copy/paste ❌ or ✔️, and makes it easier to update the checklist after adding the changelog (since you don't have to edit the PR's description, you can just check the box.
