### ISSUE TITLE
Release 1.5.0 checklist

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1322]
In the steps below, "all four repos" refers to open-sdg, sdg-build, sdg-translations, and jekyll-open-sdg-plugins.

# Releasing the "beta1" version (eg 1.4.0-beta1)

* [x] Create a new dev branch (eg, 1.5.0-dev) in all four repos
* [x] Make these new dev branches the default branch for all four repos
* [x] Update the ["Repository branch" in Weblate](https://hosted.weblate.org/settings/sdg-translations/general/#vcs) to point to the new dev branch
* [x] In the new dev branch for open-sdg, make sure that tests run against the new dev branches for the other repos, by updating these files:
     * tests/site/Gemfile
     * tests/data/requirements.txt
* [x] Push the beta tag for all four repos
* [x] Create a PR against the old dev branch with upgrade instructions (specific to the beta1 branches) and tweaks to the docs/updates.md file
* [x] Bump the version in [this file](https://github.com/open-sdg/jekyll-open-sdg-plugins/blob/1.6.0-dev/lib/jekyll-open-sdg-plugins/version.rb) and publish the beta1 version of jekyll-open-sdg-plugins to rubygems.org, eg:
    * `gem build jekyll-open-sdg-plugins.gemspec`
    * `gem push jekyll-open-sdg-plugins-1.5.0.pre.beta1.gem`
* [x] Do testing, pushing new beta2/beta3/etc tags as needed

# Releasing the new version (eg 1.4.0)

## A. Changelogs and versions

1. [x] Make sure these open-sdg files have been updated:
    * docs/changelog.md
    * docs/updates.md
2. [x] Make sure these sdg-build files have been updated:
    * CHANGELOG.md
    * README.md
    * setup.py (version number)
3. [x] Make sure these sdg-translations files have been updated:
    * www/changelog.md (currently out of date)
4. [x] Make sure these jekyll-open-sdg-plugins files have been updated:
    * lib/jekyll-open-sdg-plugins/version.rb (version number)
5. [x] Make sure the upgrade instructions have been added to docs/upgrades/.

## B. Translations

1. [x] Make sure that any new translations have been translated into all languages. Use machine translation for this, and mark them as "Needs edit" so that a human translator can eventually edit/approve. **This has now been automated for all translation groups except for global_indicators, global_targets, and global_goals, thanks to the "Automatic translation" add-on in Weblate.**
2. [x] Make sure that Weblate has no pending commits and the Weblate pull-request has been merged.

## C. Tags and branches

1. [x] Push the new tag for all four repos.
2. [x] Merge the old dev branch into the new dev branch for all four repos. Eg, if releasing version 1.3.0, merge 1.3.0-dev into 1.4.0-dev.
3. [x] Merge the old dev branch into the master branch for all four repos. Eg, if releasing version 1.3.0, merge 1.3.0-dev into master.

## D. Packages

1. [x] Build ("gem build") and push ("gem push") the jekyll-open-sdg-plugins gem to rubygems.org
2. (Not implemented yet) Publish sdg-build to pypi.org.

## E. Starter repositories

1. [x] Update the open-sdg-data-starter to point to the new tags, by updating these files:
    * https://github.com/open-sdg/open-sdg-data-starter/blob/develop/config_data.yml
    * https://github.com/open-sdg/open-sdg-data-starter/blob/develop/scripts/requirements.txt
2. [x] Update the open-sdg-site-starter to point to the new tags, by updating these files:
    * https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml
    * https://github.com/open-sdg/open-sdg-site-starter/blob/develop/Gemfile
3. [x] Update the open-sdg-simple-starter to point to the new tags, by updating these files:
    * https://github.com/open-sdg/open-sdg-simple-starter/blob/develop/Gemfile
    * https://github.com/open-sdg/open-sdg-simple-starter/blob/develop/requirements.txt
    * https://github.com/open-sdg/open-sdg-simple-starter/blob/develop/config_site.yml
    * https://github.com/open-sdg/open-sdg-simple-starter/blob/develop/config_data.yml
4. [ ] If this release contains any "recommended but optional" features, configure them in the starter repos as needed.

## F. Outreach

1. [x] Create a release video
2. [x] Create a post on open-sdg.org
3. [x] Social media announcements

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner A few questions:
1. Do you think we should make the hide_single_series and hide_single_unit set to "true" in the starter repos?
2. I was also going to ask if we should make the x_axis_label set to "Year" in the starter repos, but I realized that we do not have the word "Year" translated. I'm not sure if we would even have wanted to set that as a default -- just mentioning it. If we do ever decide to make it a default, we will need to translate whatever we pick.
3. I realized I forgot to mention in the upgrade instructions about the ShareThis support being removed. Do you think that's OK, since we don't know of anyone using it?

**Comment by phillipgardiner** [comment]
@brockfanning can't comment on 1 and 3, but i'd say don't need to set x-axis default to year. I'm assuming the default would be 'blank'. It was primarily the UK pushing for the label so I guess we would change that locally.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I think re. 1, if it's best practice for radio buttons not to show when there is only one, then I think yes, set them as true. Re. 3, I think that's fine

**Comment by phillipgardiner** [comment]
@brockfanning sorry didn't totally get my head around number 1. Yes as Lucy said it is best practice so set as true :)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner Similar question: Do we want to make the cookie consent form default to enabled for new sites?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just been looking at this blog: https://www.termsfeed.com/blog/cookie-consent-outside-eu/

From what I can see, cookie consent isn't widely required outside of the EU and EEA so I'm thinking we should not put it on by default but put somewhere in documentation that it's strongly recommended that you turn it on if an EU or EEA country, maybe even put as a next step from the quick start.

@AnnCorp what are your thoughts?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning just had a thought - we will also need to swap out the favicons in the site-starter repo

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin @brockfanning agree with Lucy's solution - make sure well documented but not default enabled. Could we capture in a note somewhere re needing guidance on setting up cookie consent stuff etc pls (if not already captured).

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp Brock has put together some guidance for cookies and privacy here: https://open-sdg.readthedocs.io/en/latest/cookies/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I missed your note before, sorry - just submitted this: https://github.com/open-sdg/open-sdg/pull/1361

**Comment by brockfanning** [comment]
Will add a note about hide_single_unit and hide_single_series as "recommended" config settings in the 1.5.0 upgrade docs.

**Comment by brockfanning** [comment]
Will follow up with Matt about social media.
